services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    depends_on:
      - web

  # Backend service
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/app_db
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - BACKEND_CORS_ORIGINS=http://localhost,http://5.161.185.159
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: >
      sh -c "flask db upgrade &&
             gunicorn --bind 0.0.0.0:5000 wsgi:application --reload"

  # Database service
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: 