"""update_project_fields_and_status_enum

Revision ID: 9cfa5c8a8bb8
Revises: ac169e07ba49
Create Date: 2024-03-19

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cfa5c8a8bb8'
down_revision = 'ac169e07ba49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add the 'progress' column
    op.add_column('projects', sa.Column('progress', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # Step 2: Rename 'due_date' to 'end_date'
    op.alter_column('projects', 'due_date', new_column_name='end_date', existing_type=sa.DateTime(), nullable=True)

    # Step 3: Modify project_status_enum
    # First, update any 'cancelled' status to 'on-hold'
    op.execute("UPDATE projects SET status = 'on-hold' WHERE status = 'cancelled'")

    # Create new enum type
    op.execute("CREATE TYPE project_status_enum_new AS ENUM('planning', 'active', 'completed', 'on-hold')")
    
    # Update the column to use the new type
    op.execute("ALTER TABLE projects ALTER COLUMN status TYPE project_status_enum_new USING status::text::project_status_enum_new")
    
    # Set the default value
    op.execute("ALTER TABLE projects ALTER COLUMN status SET DEFAULT 'planning'")
    
    # Drop the old enum type
    op.execute('DROP TYPE project_status_enum')
    
    # Rename the new enum type to the original name
    op.execute('ALTER TYPE project_status_enum_new RENAME TO project_status_enum')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Revert project_status_enum modification
    op.execute("CREATE TYPE project_status_enum_old AS ENUM('planning', 'active', 'completed', 'on-hold', 'cancelled')")
    op.execute("ALTER TABLE projects ALTER COLUMN status TYPE project_status_enum_old USING status::text::project_status_enum_old")
    op.execute("ALTER TABLE projects ALTER COLUMN status SET DEFAULT 'planning'")
    op.execute('DROP TYPE project_status_enum')
    op.execute('ALTER TYPE project_status_enum_old RENAME TO project_status_enum')

    # Step 2: Rename 'end_date' back to 'due_date'
    op.alter_column('projects', 'end_date', new_column_name='due_date', existing_type=sa.DateTime(), nullable=True)

    # Step 3: Remove the 'progress' column
    op.drop_column('projects', 'progress')
    
    # ### end Alembic commands ###
